[app_servers]
# Reemplaza la IP por la IP pública de tu servidor de AWS generada en los outputs de Terraform
app_server_aws ansible_host=3.85.192.12 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/payfast-key.pem
